---
  - hosts: winsvr
    vars:
      _val_1: "installed: 1"
      _const_val: "1"
      _flag: false
      _condition_1: true
      _condition_2: true
      _condition_3: true

    tasks:
      - debug:
          msg: "ok"
        when:
          - _condition_1 == true
          - _condition_2 == true
          - _condition_3 == true

      - debug:
          msg: "Do ie esc disable"
        when: not _flag and "1" in _val_1

      - debug:
          msg: "Do ie esc disable"
        when:
          - not _flag
          - _const_val in _val_1

      # in 演算子について確認
      # 下の結果が上と違うのは
      # <要素> in <集合> 
      # ある<要素>がある<集合>に含まれるかどうかを評価するから！
      # 左辺と右辺で意味が違うということを改めて
      - debug:
          msg: "Do ie esc disable"
        when:
          - not _flag
          - _val_1 in "1"

      # syntax error
      #- debug:
      #    msg: "Do ie esc disable"
      #  when:
      #    - not _flag
      #    - "1" in _val_1
...