---
    - name: ワークグループを設定する
      hosts: winsvr
      gather_facts: false

      tasks:
        - name: set workgroup
          win_domain_membership:
            workgroup_name: "{{ hv_workgroup_name }}"
            domain_admin_user: "{{ hv_domain_admin_user }}"
            domain_admin_password: "{{ hv_domain_admin_password }}"
            state: "{{ hv_win_domain_membership_state }}"
          register: _result_domain_membership

        - name: do reboot
          win_reboot:
          when: _result_domain_membership.reboot_required
...