---
    - name: IPv6 を無効にする
      hosts: winsvr
      gather_facts: true

      tasks:
        - name: disable ipv6
          win_shell: Disable-NetAdapterBinding -Name "イーサネット" -ComponentID ms_tcpip6
          async: 100
          poll: 0

        - name: confirm ipv6
          win_shell: Get-NetAdapterBinding -Name "イーサネット"-ComponentID ms_tcpip6
          register: _result_status

        - name: debug display _result_status
          debug:
            var: _result_status
...