---
    - name: 疎通確認と facts の収集
      hosts: winsvr
      gather_facts: true

      tasks:
        - name: ping to windows server
          win_ping:
          register: _result_ping

        - name: debug
          debug:
            var: _result_ping

        - name: get windows server informations
          debug: var=ansible_facts

        - name: systeminfo command
          win_command: systeminfo
          register: _result_info
        - debug: var=_result_info
...