---
  # TODO:改善の必要あり
    - hosts: winsvr
      gather_facts: true

      tasks:
        #- name: Display win_facs
        #  debug:
        #    var: ansible_facts

        - name: "DefaultGatewayが設定存在するか確認する"
          win_shell: "{% raw %}Get-WmiObject Win32_NetworkAdapterConfiguration | Where-Object{$_.IPEnabled -eq 'TRUE'} | Format-List DefaultIPGateway{% endraw %}"
          register: _result_shell

        #- debug:
        #    var: _result_shell

        - name: "静的 IP アドレスを設定する（DefaultGatewayが設定されていない）"
          win_shell: "Get-NetIPAddress -interfaceAlias 'イーサネット' -AddressFamily IPv4 | New-NetIpAddress -IpAddress {{ hv_static_ipv4 }} -PrefixLength 24 -DefaultGateway {{ hv_default_gateway }}"
          async: 100 # Using "fire-and-forget" asynchronous execution for this task, otherwise it will always fail and timeout
          poll: 0
          when: _result_shell.stdout == ""

        #- debug:
        #    msg: "Get-NetIPAddress -interfaceAlias 'イーサネット' -AddressFamily IPv4 | New-NetIpAddress -IpAddress {{ hv_static_ipv4 }} -PrefixLength 24"

        - name: "静的 IP アドレスを設定する（DefaultGatewayが設定されている）"
          win_shell: "Get-NetIPAddress -interfaceAlias 'イーサネット' -AddressFamily IPv4 | New-NetIpAddress -IpAddress {{ hv_static_ipv4 }} -PrefixLength 24"
          #win_shell: "Get-NetIPAddress -interfaceAlias 'イーサネット' -AddressFamily IPv4 | Set-NetIPAddress -InterfaceAlias 'イーサネット' -AddressFamily IPv4 -IPAddress {{ hv_static_ipv4 }} -PrefixLength 24"
          async: 100 # Using "fire-and-forget" asynchronous execution for this task, otherwise it will always fail and timeout
          poll: 0
          when: _result_shell.stdout != ""

        - name: Change ansible's ip address for each host
          set_fact:
            ansible_host: "{{ hv_static_ipv4 }}"
  
        - name: Wait for the hosts network interface to come back up
          local_action:
            module: wait_for
            host: "{{ ansible_host }}"
            port: 5985
            delay: 10
            state: started
            timeout: 30
          register: _result_wait
...