---
    - hosts: winsvr
      gather_facts: false

      tasks:
        - name: Start NTP service (w32time)
          win_service:
            name: w32time
            state: started
            start_mode: auto

        - name: Configure NTP
          win_command: w32tm /config /manualpeerlist:"{{ gv_peers }}" /reliable:yes /update
          args:
            output_encoding_override: shift_jis
          changed_when: false

        - name: confirm
          win_command: w32tm /query /status
          args:
            output_encoding_override: shift_jis
...