---
    - name: administrator のパスワードを変更する
      hosts: win_test
      gather_facts: false

      tasks:
        # administrator のパスワードを変更する
        #- name: do change
        #  win_user:
        #    name: administrator
        #    password: "{{ hv_new_local_adm_psswd }}"
        #    state: present
        # Ansibleが接続に使用しているユーザーのパスワードを変更するが上手くいっていない
        - name: add ansible user
          win_user:
            name: ansible
            password: workinguser%TMP_200819-jp
            groups:
              - Administrators

        - name: switch to ansible user
          set_fact:
            ansible_user: ansible
            ansible_password: workinguser%TMP_200819-jp

        - name: Administratorのパスワードを変更する
          win_user:
            name: Administrator
            password: "{{ hv_new_local_adm_psswd }}"
            state: present

        - name: change administrator user
          set_fact:
            ansible_user: Administrator
            ansible_password: "{{ hv_new_local_adm_psswd }}"

        - name: delete ansible user
          win_user:
            name: ansible
            state: absent
...