---
    - hosts: winsvr
      gather_facts: false

      tasks:
        - name: Configure IE proxy settings to apply to all users
          win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
            name: ProxySettingsPerUser
            data: 0
            type: dword
            state: present

        - name: Configure IE LAN settings
          win_inet_proxy:
            auto_detect: no
            proxy: "{{ gv_proxy }}"
            bypass: "{{ gv_list_bypass }}"

        #- name: Configure IE LAN settings
        #  win_inet_proxy:
        #    auto_detect: no
        #    proxy: 
        #      http: example.com:8080
        #      https: sample.com:443
        #    bypass:
        #      - <local>
        #      - <-loopback>
        #      - 10.*.*.*
        #      - "*.hogehoge.com"
...