---
    # administrator のパスワードを変更する
    - hosts: winsvr
      gather_facts: false

      tasks:
        - name: Change the administrator password
          win_user:
            name: administrator
            password: "{{ hv_new_local_adm_psswd }}"
            state: present
...