---
    - name: Java Update の無効化
      hosts: winsvr
      gather_facts: false

      vars:
        _disable_java_update:
            - path: HKLM:\SOFTWARE\JavaSoft\Java Update\Policy
              name: EnableJavaUpdate
              data: 0

      tasks:
        - name: disable Java Update
          win_regedit:
            path: "{{ item.path }}"
            name: "{{ item.name }}"
            data: "{{ item.data }}"
            type: DWORD
            state: present
          with_items: "{{ _disable_java_update }}"
...