---
    - name: インターネットエクスプローラーのスタートページを設定する
      hosts: winsvr
      gather_facts: false

      tasks:
        - name: set internet explorer start page
          win_regedit:
            path: HKCU:\Software\Microsoft\Internet Explorer\Main\
            name: start page
            data: "{{ gv_start_page_url }}"
...
